import { AllTranslations } from './types';

export const UI_TRANSLATIONS: AllTranslations = {
  en: {
    // General
    'price': 'Price',
    'admin_panel': 'Admin Panel',
    'customer_view': 'Customer View',
    'language': 'Language',
    'close': 'Close',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'all': 'All',
    'select_theme': 'Select Theme',
    'chefs_specials': 'Chef\'s Specials',
    'saving': 'Saving...',

    // Admin Panel
    'manage_menu_items': 'Manage Menu Items',
    'manage_categories': 'Manage Categories',
    'settings': 'Settings',
    'cafe_settings': 'Cafe Settings',
    'cafe_name_en': 'Cafe Name (English)',
    'cafe_name_fa': 'Cafe Name (Persian)',
    'logo_url': 'Logo URL',
    'logo_preview': 'Logo Preview',
    'theme_settings': 'Theme Settings',
    'save_settings': 'Save Settings',
    'add_new_item': 'Add New Item',
    'edit_item': 'Edit Item',
    'add_new_category': 'Add New Category',
    'edit_category': 'Edit Category',
    'item_name_en': 'Item Name (English)',
    'item_name_fa': 'Item Name (Persian)',
    'description_en': 'Description (English)',
    'description_fa': 'Description (Persian)',
    'image_url': 'Image URL',
    'category': 'Category',
    'select_category': 'Select a category',
    'category_name_en': 'Category Name (English)',
    'category_name_fa': 'Category Name (Persian)',
    'actions': 'Actions',
    'confirm_delete_item': 'Are you sure you want to delete this item?',
    'confirm_delete_category': 'Are you sure you want to delete this category? This will also permanently delete all menu items inside it.',
    'name': 'Name',
    'description': 'Description',
    'no_items': 'No items found in this category.',
    'no_categories': 'No categories found. Please add one.',
    'no_items_in_db': 'No items found. Please add one.',
    'search_by_name': 'Search by name...',
    'no_items_match_search': 'No items match your search.',
    'display_settings': 'Display Settings',
    'category_display_style': 'Category Display Style',
    'style_tabs': 'Tabs (Simple text)',
    'style_thumbnails': 'Thumbnails (Circular images)',
    'admin_login': 'Admin Login',
    'username': 'Username',
    'password': 'Password',
    'sign_in': 'Sign In',
    'incorrect_credentials': 'Incorrect username or password.',
    'logout': 'Logout',
  },
  fa: {
    // General
    'price': 'قیمت',
    'admin_panel': 'پنل مدیریت',
    'customer_view': 'نمای مشتری',
    'language': 'زبان',
    'close': 'بستن',
    'save': 'ذخیره',
    'cancel': 'لغو',
    'delete': 'حذف',
    'edit': 'ویرایش',
    'all': 'همه',
    'select_theme': 'انتخاب تم',
    'chefs_specials': 'ویژه سرآشپز',
    'saving': 'در حال ذخیره...',

    // Admin Panel
    'manage_menu_items': 'مدیریت آیتم‌های منو',
    'manage_categories': 'مدیریت دسته‌بندی‌ها',
    'settings': 'تنظیمات',
    'cafe_settings': 'تنظیمات کافه',
    'cafe_name_en': 'نام کافه (انگلیسی)',
    'cafe_name_fa': 'نام کافه (فارسی)',
    'logo_url': 'آدرس لوگو',
    'logo_preview': 'پیش‌نمایش لوگو',
    'theme_settings': 'تنظیمات تم',
    'save_settings': 'ذخیره تنظیمات',
    'add_new_item': 'افزودن آیتم جدید',
    'edit_item': 'ویرایش آیتم',
    'add_new_category': 'افزودن دسته‌بندی جدید',
    'edit_category': 'ویرایش دسته‌بندی',
    'item_name_en': 'نام آیتم (انگلیسی)',
    'item_name_fa': 'نام آیتم (فارسی)',
    'description_en': 'توضیحات (انگلیسی)',
    'description_fa': 'توضیحات (فارسی)',
    'image_url': 'آدرس تصویر',
    'category': 'دسته‌بندی',
    'select_category': 'یک دسته‌بندی انتخاب کنید',
    'category_name_en': 'نام دسته‌بندی (انگلیسی)',
    'category_name_fa': 'نام دسته‌بندی (فارسی)',
    'actions': 'عملیات',
    'confirm_delete_item': 'آیا از حذف این آیتم مطمئن هستید؟',
    'confirm_delete_category': 'آیا از حذف این دسته‌بندی مطمئن هستید؟ این عمل تمام آیتم‌های منوی داخل آن را نیز برای همیشه حذف خواهد کرد.',
    'name': 'نام',
    'description': 'توضیحات',
    'no_items': 'هیچ آیتمی در این دسته‌بندی یافت نشد.',
    'no_categories': 'هیچ دسته‌بندی یافت نشد. لطفا یکی اضافه کنید.',
    'no_items_in_db': 'هیچ آیتمی یافت نشد. لطفا یکی اضافه کنید.',
    'search_by_name': 'جستجو بر اساس نام...',
    'no_items_match_search': 'هیچ آیتمی با جستجوی شما مطابقت ندارد.',
    'display_settings': 'تنظیمات نمایش',
    'category_display_style': 'سبک نمایش دسته‌بندی‌ها',
    'style_tabs': 'تب‌ها (متن ساده)',
    'style_thumbnails': 'تصاویر کوچک (دایره‌ای)',
    'admin_login': 'ورود مدیر',
    'username': 'نام کاربری',
    'password': 'رمز عبور',
    'sign_in': 'ورود',
    'incorrect_credentials': 'نام کاربری یا رمز عبور اشتباه است.',
    'logout': 'خروج',
  }
};